apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pact-broker
  name: pact-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pact-broker
  template:
    metadata:
      labels:
        run: pact-broker
    spec:
      containers:
      - image: pactfoundation/pact-broker:latest
        name: pact-broker
        env:
        - name: PACT_BROKER_DATABASE_USERNAME
          value: "pactbroker"
        - name: PACT_BROKER_DATABASE_PASSWORD
          value: "pactbroker"
        - name: PACT_BROKER_DATABASE_HOST
          value: "pact-postgres-service"
        - name: PACT_BROKER_DATABASE_NAME
          value: "pact"
        ports:
        - containerPort: 9292

---
apiVersion: v1
kind: Service
metadata:
  name: pact-broker-service
spec:
  type: NodePort
  ports:
  - port: 9292
    name: web
    targetPort: 9292
    nodePort: 30111
  selector:
    run: pact-broker
